// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbmrbsameetutimmmwoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpibXJic2FtZWV0dXRpbW1td29jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0OTkzNzUsImV4cCI6MjA1OTA3NTM3NX0.cPA7dhhyCwVko61FY6RNiQTlHTRgCp2aPJ1SYfAfMNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);